name: CI
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  iOS:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: '/Applications/Xcode_15.1.app/Contents/Developer'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      - uses: actions/cache@v4
        with:
          path: Example/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Delete Xcode.app
        run: sudo rm -rf /Applications/Xcode.app
      - name: Install Pods
        run: bundle exec pod install --repo-update --project-directory=Example
      - name: Test
        run: make test
      - name: Lint
        run: make lint
